name: "Check Pull Request labels"

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - dev
    types:
      - labeled
      - unlabeled

permissions: {}

jobs:
  check_labels:
    name: "Check Pull Request labels"
    runs-on: ubuntu-latest
    steps:
      - name: Check the labels
        uses: ludeeus/action-require-labels@1.1.0
        with:
          labels: >-
            bugfix, breaking-change, new-feature, code-quality, new-integration, deprecation, dependency
